#!/bin/bash

#echo "darbu"

# Define command-line arguments

RESOURCE_TYPE=$3

#echo $RESOURCE_TYPE
#echo $1
#echo $2
#echo "kubectl $2 $RESOURCE_TYPE -n $1 | tail -n +2 | while read line"
#exit

# Retrieve resource usage statistics from Kubernetes
kubectl $2 $RESOURCE_TYPE -n $1 | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory" 
  echo "$RESOURCE_TYPE, $1, $NAME, $CPU, $MEMORY"
done